export const SELECT_NAMESPACE = 'SELECT_NAMESPACE'
export const SELECT_KEY = 'SELECT_KEY'
export const TOGGLE_NAMESPACE = 'TOGGLE_NAMESPACE'
export const VALUE_CHANGE = 'VALUE_CHANGE'
export const CREATE_NAMESPACE = 'CREATE_NAMESPACE'
export const OPEN_DIALOG = 'OPEN_DIALOG'
export const CLOSE_DIALOG = 'CLOSE_DIALOG'
export const CHANGE_WINDOW = 'CHANGE_WINDOW'
export const SEARCH_VALUE_CHANGE = 'SEARCH_VALUE_CHANGE'
export const LOAD_VALUE = 'LOAD_VALUE'

export const FILTER_BY_SEARCH = 'FILTER_BY_SEARCH'

export const SNACKBAR_EMPTY = 'SNACKBAR_EMPTY'

/**
 *  Async Action Types
 */

/**
 *  Namespaces
 */
export const FETCH_NAMESPACES_FULFILLED = 'FETCH_NAMESPACES_FULFILLED'
export const FETCH_NAMESPACES_PENDING = 'FETCH_NAMESPACES_PENDING'
export const FETCH_NAMESPACES_REJECTED = 'FETCH_NAMESPACES_REJECTED'

/**
 *  Keys
 */
export const FETCH_KEYS_FULFILLED = 'FETCH_KEYS_FULFILLED'
export const FETCH_KEYS_PENDING = 'FETCH_KEYS_PENDING'
export const FETCH_KEYS_REJECTED = 'FETCH_KEYS_REJECTED'

export const FETCH_VALUE_FULFILLED = 'FETCH_VALUE_FULFILLED'
export const FETCH_VALUE_PENDING = 'FETCH_VALUE_PENDING'
export const FETCH_VALUE_REJECTED = 'FETCH_VALUE_REJECTED'

export const UPDATE_VALUE_FULFILLED = 'UPDATE_VALUE_FULFILLED'
export const UPDATE_VALUE_PENDING = 'UPDATE_VALUE_PENDING'
export const UPDATE_VALUE_REJECTED = 'UPDATE_VALUE_REJECTED'

export const CREATE_VALUE_FULFILLED = 'CREATE_VALUE_FULFILLED'
export const CREATE_VALUE_PENDING = 'CREATE_VALUE_PENDING'
export const CREATE_VALUE_REJECTED = 'CREATE_VALUE_REJECTED'

export const DELETE_KEY_FULFILLED = 'DELETE_KEY_FULFILLED'
export const DELETE_KEY_PENDING = 'DELETE_KEY_PENDING'
export const DELETE_KEY_REJECTED = 'DELETE_KEY_REJECTED'

export const DELETE_NAMESPACE_FULFILLED = 'DELETE_NAMESPACE_FULFILLED'
export const DELETE_NAMESPACE_PENDING = 'DELETE_NAMESPACE_PENDING'
export const DELETE_NAMESPACE_REJECTED = 'DELETE_NAMESPACE_REJECTED'

/**
 *  Generic
 */
export const REQUEST_ASYNC_ACTION = 'REQUEST_ASYNC_ACTION'
export const REJECT_ASYNC_ACTION = 'REJECT_ASYNC_ACTION'

export const SET_EDIT_WINDOW = 'SET_EDIT_WINDOW'
export const SET_BROWSER_WINDOW = 'SET_BROWSER_WINDOW'
export const SET_BROWSER_LIST = 'SET_BROWSER_LIST'

/**
 * Navigation
 */

export const SET_IGNORE_NEXT_CONFIRM_NAVIGATION =
    'SET_IGNORE_NEXT_CONFIRM_NAVIGATION'
