

export const FETCH_NAMESPACES_FULFILLED = 'FETCH_NAMESPACES_FULFILLED';
export const FETCH_KEYS_FULFILLED = 'FETCH_KEYS_FULFILLED';
export const FETCH_VALUE_FULFILLED = 'FETCH_VALUE_FULFILLED'
export const FETCH_HISTORY_FULFILLED = 'FETCH_HISTORY_FULFILLED'

export const REQUEST_ASYNC_ACTION = 'REQUEST_ASYNC_ACTION';
export const REJECT_ASYNC_ACTION = 'REJECT_ASYNC_ACTION';

export const SELECT_NAMESPACE = 'SELECT_NAMESPACE';
export const SELECT_KEY = 'SELECT_KEY';
