


export const FETCH_DATASTORE_NAMESPACES = 'FETCH_DATASTORE_NAMESPACES';
export const FETCH_DATASTORE_NAMESPACES_PENDING = 'FETCH_DATASTORE_NAMESPACES_PENDING';
export const FETCH_DATASTORE_NAMESPACES_FULFILLED = 'FETCH_DATASTORE_NAMESPACES_FULFILLED';
export const FETCH_DATASTORE_NAMESPACES_REJECTED = 'FETCH_DATASTORE_NAMESPACES_REJECTED';

export const FETCH_DATASTORE_KEYS = 'FETCH_DATASTORE_KEYS';
export const FETCH_DATASTORE_KEYS_PENDING = 'FETCH_DATASTORE_KEYS_PENDING';
export const FETCH_DATASTORE_KEYS_FULFILLED = 'FETCH_DATASTORE_KEYS_FULFILLED';
export const FETCH_DATASTORE_KEYS_REJECTED = 'FETCH_DATASTORE_KEYS_REJECTED';

export const FETCH_DATASTORE_VALUE = 'FETCH_DATASTORE_VALUE';
export const FETCH_DATASTORE_VALUE_PENDING = 'FETCH_DATASTORE_VALUE_PENDING';
export const FETCH_DATASTORE_VALUE_FULFILLED = 'FETCH_DATASTORE_VALUE_FULFILLED';
export const FETCH_DATASTORE_VALUE_REJECTED = 'FETCH_DATASTORE_VALUE_REJECTED';

export const SELECT_NAMESPACE = 'SELECT_NAMESPACE';
export const SELECT_KEY = 'SELECT_KEY';
