

export const FETCH_DATASTORE_NAMESPACES = 'FETCH_DATASTORE_NAMESPACES';
export const FETCH_DATASTORE_NAMESPACES_PENDING = 'FETCH_DATASTORE_NAMESPACES_PENDING';
export const FETCH_DATASTORE_NAMESPACES_FULFILLED = 'FETCH_DATASTORE_NAMESPACES_FULFILLED';
export const FETCH_DATASTORE_NAMESPACES_REJECTED = 'FETCH_DATASTORE_NAMESPACES_REJECTED';