export const NEW_NAMESPACE = 'NEW_NAMESPACE';
export const NEW_KEY = 'NEW_KEY';
export const CONFIRM_DELETE_NAMESPACE = 'CONFIRM_DELETE_NAMESPACE';
export const CONFIRM_DELETE_KEY = 'CONFIRM_DELETE_KEY';
export const ERROR_DIALOG = 'ERROR_DIALOG';
